title: <p align="center"> Trystan Geoffre </p>

#logo: "/images/picture.png?raw=true"

description:
  <p align="center">
  <a href="CVMinimal_Trystan_Geoffre.pdf">Minimal Resume</a> |
  <a href="CV_Trystan_Geoffre.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/trystan-geoffre-03/">LinkedIn</a> |
  <a href="https://github.com/trystan-geoffre">GitHub</a>
  </p>
  
  <p align="justify">
  I'm a self-taught passionate Data Scientist & Problem Solver
  <br><br>
  
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
#google_analytics: UA-145578661-1 # Google Analytics tracking ID
